import '../public/assets/css/bootstrap.min.css'
import '../public/assets/css/fontawesome.min.css'
import '../public/assets/css/themify-icons.css'
import '../public/assets/css/elegant-icons.css'
import '../public/assets/css/flaticon-set.css'
import '../public/assets/css/magnific-popup.css'
import '../public/assets/css/swiper-bundle.min.css'
import '../public/assets/css/animate.css'
import '../public/assets/css/validnavs.css'
import '../public/assets/css/helper.css'
import '../public/assets/css/unit-test.css'
import '../public/assets/css/style.css'

export const metadata = {
  title: 'Traductor e Intérprete Jurado',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon" />
      </head>
      <body>{children}</body>
    </html>
  )
}
